# Generated by Django 4.2.3 on 2023-07-17 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0011_barbershoppicture'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(default=1, limit_choices_to={'barbershop': django.db.models.expressions.OuterRef('barbershop')}, on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbershopservice'),
            preserve_default=False,
        ),
    ]
