# Generated by Django 4.2.3 on 2023-07-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0011_barbershoppicture'),
        ('reservation', '0002_reservation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbershopservice'),
        ),
    ]
