# Generated by Django 4.2.3 on 2023-08-06 19:33

import BarberBook.client.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), BarberBook.client.validators.validate_client_city_name]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), BarberBook.client.validators.validate_client_name]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), BarberBook.client.validators.validate_client_name]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8), BarberBook.client.validators.validate_client_phone_number]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client-profile-pictures', validators=[BarberBook.client.validators.validate_client_picture_file_size]),
        ),
    ]
