# Generated by Django 4.2.3 on 2023-07-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
