# Generated by Django 4.2.3 on 2023-07-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_barbershopprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopprofile',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
