# Generated by Django 4.2.3 on 2023-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_barbershopprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopprofile',
            name='barbershop_picture',
            field=models.ImageField(blank=True, null=True, upload_to='barbershop-profile-pictures'),
        ),
    ]
