# Generated by Django 4.2.3 on 2023-07-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0007_alter_barbershopworkinghours_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbershopworkinghours',
            options={'verbose_name_plural': 'Barbershop Working Hours'},
        ),
    ]
