# Generated by Django 4.2.3 on 2023-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0008_alter_barbershopworkinghours_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopprofile',
            name='geolocation_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='barbershopprofile',
            name='geolocation_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
