# Generated by Django 4.2.3 on 2023-07-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0009_barbershopprofile_geolocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopprofile',
            name='geolocation_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='geolocation_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
