# Generated by Django 4.2.3 on 2023-07-16 20:04

import BarberBook.barbershop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0010_alter_barbershopprofile_geolocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarbershopPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=BarberBook.barbershop.models.barbershop_picture_upload_to)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbershopprofile')),
            ],
        ),
    ]
