# Generated by Django 4.2.3 on 2023-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0012_alter_barbershopworkinghours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopprofile',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
