# Generated by Django 4.2.3 on 2023-08-06 19:33

import BarberBook.barbershop.models
import BarberBook.barbershop.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0014_alter_barbershoppicture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershoppicture',
            name='image',
            field=models.ImageField(upload_to=BarberBook.barbershop.models.barbershop_picture_upload_to, validators=[BarberBook.barbershop.validators.validate_barbershop_picture_file_size]),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='barbershop_picture',
            field=models.ImageField(blank=True, null=True, upload_to='barbershop-profile-pictures', validators=[BarberBook.barbershop.validators.validate_barbershop_picture_file_size]),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), BarberBook.barbershop.validators.validate_barbershop_city_name]),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='geolocation_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='geolocation_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='barbershopprofile',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='barbershopservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='barbershopservice',
            name='service_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='category_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
