# Generated by Django 4.2.3 on 2023-08-08 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0016_alter_barbershopprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopprofile',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
