# Generated by Django 4.2.3 on 2023-07-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_alter_servicecategory_options_barbershopworkinghours'),
        ('barber', '0003_rename_user_barber_barbershop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbershopprofile'),
        ),
    ]
