# Generated by Django 4.2.3 on 2023-08-06 19:33

import BarberBook.barber.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_alter_barber_barbershop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='barber_picture',
            field=models.ImageField(blank=True, null=True, upload_to='barber-profile-pictures', validators=[BarberBook.barber.validators.validate_barber_picture_file_size]),
        ),
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), BarberBook.barber.validators.validate_name]),
        ),
    ]
